### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by adrianObel** [adrianObel/koa2-api-boilerplate#1]
Going through a few options regarding docs. 

I'm thinking an inline solution (jsdoc style) instead of having to maintain a separate mark up file would be best.

**Comment by juanda99** [comment]
http://apidocjs.com/ ?

**Comment by adrianObel** [comment]
@juanda99  I've been looking at apidoc for a bit now, actually. I haven't used it very extensively, looks good tho!
