### ISSUE TITLE
Async/Await in tests?

### ISSUE THREAD

**Issue by hoodsy** [adrianObel/koa2-api-boilerplate#11]
I've been following this project as a good baseline for testing my Koa2 API, and was wondering what you all think about using async/await with Mocha/Chai/Supertest.

It seems fitting considering the entire API uses async/await as well.

**Comment by adrianObel** [comment]
@hoodsy You make a good point, actually. We could use something like [supertest-as-promised](https://github.com/WhoopInc/supertest-as-promised).

We then could write tests like

```
try {
  const res = await request
    .post('/auth')
    .set('Accept', 'application/json')
    .send({ username: 'test', password: 'pass' })
    .expect(200)

  res.body.user.should.have.property('username')
  res.body.user.username.should.equal('test')
  expect(res.body.user.password).to.not.exist

  context.user = res.body.user
  context.token = res.body.token

  done()
} catch (err) { done(err) }
```

**Comment by hoodsy** [comment]
@adrianObel Hmm.. the consistency is nice. As you say though, having to wrap everything in try/catch may be a bit tedious. 

Maybe I'll experiment with this in my own project. Thanks for sharing 😁
