### ISSUE TITLE
Test runs

### ISSUE THREAD

**Issue by arcanewater** [adrianObel/koa2-api-boilerplate#14]
Just pulled project and tested it a bit, but what to do with command npm test? As its fails mostly because of ctx input? In a way of: TypeError: Cannot read property 'body' of undefined ?

**Comment by adrianObel** [comment]
@arcanewater Could you post your stack trace? I've never run into this problem

**Comment by arcanewater** [comment]
@adrianObel Not sure yet, i switched today to Windows and want to run it here (tomorow i post the error from Mac), but on Windows it says 

> 'NODE_ENV' is not recognized as an internal or external command,

I already tried setting with `SET NODE_ENV=test` but it does not help. Also at npm install it says

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Hope this is not playing the important role here? Should i use cross-env? And than command cross-env NODE_ENV=test ?

**Comment by adrianObel** [comment]
@arcanewater 
Oh that's because windows handles environment variables differently.
Try changing the run script to `set NODE_ENV=test&&./node_modules/.bin/mocha ....(the rest)`

**Comment by arcanewater** [comment]
Yea experimented with same thing but once i use && than it says

>  '.' is not recognized as an internal or external command,

**Comment by adrianObel** [comment]
Windows is always a pain. I don't have a windows machine handy to test it on but try using https://github.com/kentcdodds/cross-env to set the environment variable.

**Comment by arcanewater** [comment]
Yeah Windows fault :D
