### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by richardjli** [adrianObel/koa2-api-boilerplate#7]
First of all thank you very much for this boilerplate, it's great work and has been tremendously helpful for me to gain an understanding of koa2 and async/await.

I'm struggling to understand the purpose of these pieces of code in /modules/index.js:
`const lastHandler = handlers.pop();`
`return await lastHandler(ctx)`

From what I can tell this is so you can check if it is the lasthandler by checking if next exists, but why would you need to do this?

**Comment by adrianObel** [comment]
No problem at all. That's what OSS is all about :)

The `lastHandler` was introduced in #5 following a problem that @alansikora pointed out where the `ctx` was being lost after chaining multiple middleware. I haven't had a chance to test this all too well but I'm thinking of an alternative. Maybe wrapping middleware in a utils function that auto returns `next` for chaining.

Sorry I took so long to answer. Not gonna lie to you, I marked this as a question then completely forgot.
